"""add date column

Revision ID: ca9df8b77022
Revises: 86a68accd10d
Create Date: 2025-06-08 15:42:13.761330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9df8b77022'
down_revision = '86a68accd10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
