"""add title column

Revision ID: e19c5a418909
Revises: f83c39e1995e
Create Date: 2025-06-08 10:58:13.632092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c5a418909'
down_revision = 'f83c39e1995e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
