name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: postgresql+asyncpg://testuser:testpass@backend:5432/testdb

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -fsSL https://get.docker.com | sh
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start services
        run: docker-compose up -d --build

      - name: Wait for backend
        run: |
          for i in {1..10}; do
            if docker-compose exec -T app curl -s http://localhost:8000/health; then
              echo "Service ready!"
              break
            fi
            echo "Waiting... ($i/10)"
            sleep 3
          done

      - name: Run tests
        run: |
          docker-compose exec -T app pytest --cov=app --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()